# Numpy Arrays

In [8]:
import numpy as np

In [4]:
lista = list(range(10))

In [6]:
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
a = np.array(lista)

In [12]:
type(lista) 

list

In [15]:
type(a)

numpy.ndarray

In [22]:
misturados = [2.3, 9, 'nome', False]

In [23]:
for el in misturados:
    print(type(el))

<class 'float'>
<class 'int'>
<class 'str'>
<class 'bool'>


In [26]:
misturados_array = np.array(misturados)

In [27]:
misturados_array #todos elementos tem que estar em string.

array(['2.3', '9', 'nome', 'False'], dtype='<U32')

In [28]:
for el in misturados_array:
    print(type(el))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [29]:
nums = [1,2,3,4,5.0]

In [31]:
np.array(nums) #vai transformar td em float pq tem um float

array([1., 2., 3., 4., 5.])

## Numpy Array (Operações inteligentes)

In [10]:
import numpy as np

In [34]:
lista = [1,2,3,4,5]

In [35]:
array = np.array(lista)

In [41]:
array*2

array([ 2,  4,  6,  8, 10])

In [42]:
lista*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [12]:
liste = [1,3,4,5]

# Numpy Array (Indexando e Cortando _'Slicing'_)

In [25]:
import numpy as np

In [34]:
array = np.arange(1,11)

In [35]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
array[0]

1

In [37]:
array[1]

2

In [38]:
array[2]

3

In [39]:
array[6]

7

In [40]:
array[2:6] #priemiro incluso o ultimo n

array([3, 4, 5, 6])

In [43]:
array[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
array[:5]

array([1, 2, 3, 4, 5])

In [45]:
array[5:]

array([ 6,  7,  8,  9, 10])

In [46]:
array[::-1] #lista reversa

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [48]:
array[::2] #primeiro ele vai pegar 1, depois do 1 vai andando de 2 e 2 ou seja os impares

array([1, 3, 5, 7, 9])

In [50]:
array[1::2] #pega os pares

array([ 2,  4,  6,  8, 10])

In [49]:
array[::3]

array([ 1,  4,  7, 10])

# Numpy Array (Multiplas Dimensões)

In [51]:
import numpy as np

In [53]:
array = np.arange(1,13)

In [54]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
array.shape

(12,)

In [59]:
remodelado = array.reshape(6,2) #estamos remodelando o array para que ele tenha 6 linhas e 2 colunas
remodelado

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [60]:
remodelado = array.reshape(2,6) 
remodelado

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [61]:
remodelado+10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22]])

In [62]:
remodelado*2

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24]])

In [63]:
remodelado.shape

(2, 6)

In [65]:
remodelado = array.reshape(2,2,3)
remodelado

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
remodelado.shape

(2, 2, 3)

In [69]:
remodelado[1][0][1]#primeiro elemento, segundo elemento, posição da dimensão

8

# Numpy Array e Boolean

In [71]:
import numpy as np

In [72]:
array = np.arange(11)

In [73]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
cond = array > 5

In [75]:
cond

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [76]:
cond2 = (array > 5) & (array < 9)
cond2

array([False, False, False, False, False, False,  True,  True,  True,
       False, False])

In [77]:
cond3 = (array > 5) | (array < 9)
cond3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

# Numpy e Números Aleatórios

In [78]:
import numpy as np

In [80]:
array = np.random.randint(1,101,20) #randiante = inteiros vamos ter 20 valores aleatorios entre 1 e 101