# Numpy Arrays

In [8]:
import numpy as np

In [4]:
lista = list(range(10))

In [6]:
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
a = np.array(lista)

In [12]:
type(lista) 

list

In [15]:
type(a)

numpy.ndarray

In [22]:
misturados = [2.3, 9, 'nome', False]

In [23]:
for el in misturados:
    print(type(el))

<class 'float'>
<class 'int'>
<class 'str'>
<class 'bool'>


In [26]:
misturados_array = np.array(misturados)

In [27]:
misturados_array #todos elementos tem que estar em string.

array(['2.3', '9', 'nome', 'False'], dtype='<U32')

In [28]:
for el in misturados_array:
    print(type(el))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [29]:
nums = [1,2,3,4,5.0]

In [31]:
np.array(nums) #vai transformar td em float pq tem um float

array([1., 2., 3., 4., 5.])

## Numpy Array (Operações inteligentes)

In [10]:
import numpy as np

In [34]:
lista = [1,2,3,4,5]

In [35]:
array = np.array(lista)

In [41]:
array*2

array([ 2,  4,  6,  8, 10])

In [42]:
lista*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [12]:
liste = [1,3,4,5]

In [13]:
np.sqrt(liste)

array([1.        , 1.73205081, 2.        , 2.23606798])

In [14]:
narray = [2.8, 2.3, 1.1, 1.2, 1.94]

In [15]:
np.array(narray)

array([2.8 , 2.3 , 1.1 , 1.2 , 1.94])

In [16]:
narray

[2.8, 2.3, 1.1, 1.2, 1.94]

In [18]:
np.ceil(narray) #arredonda td pra cima

array([3., 3., 2., 2., 2.])

In [20]:
np.floor(narray) #arredonda td pra baixo

array([2., 2., 1., 1., 1.])

In [22]:
np.around(narray,1) #arredondamento  padrão o 1 indica as casas decimais.

array([2.8, 2.3, 1.1, 1.2, 1.9])

# Numpy Array (Indexando e Cortando _'Slicing'_)

# Numpy Array (Multiplas Dimensões)

# Numpy Array e Boolean

# Numpy e Números Aleatórios